# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc55c613c43c7d5a5e0666998470f39708d1913a45fcc8db0d90de9f1f96c8f3920b6d00ff25b24ecfb23c0ec199ccb5f31bf1d221c70d608ce1ec614cc8e90e

test:
  secret_key_base: 299f8684b85e4a3bb9c81a35310184f5fb75a0b275b6243f9a696a7daf36acfb47bde50b25a68821ece331e18ed0e8896c81bcda14fa6e10ae390a8d75c1dbe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
